<h2> Preamble </h2>

In [2]:
import h5py
import math
import numpy as np
import scipy as sp
import scipy.linalg

f = h5py.File("NLO_3B_with_nan.h5")
list(f)

['A',
 'alphas',
 'cij',
 'coulombPotential',
 'fourBodyPotential',
 'harmonicTrap',
 'isospins',
 'kinetic',
 'overlaps',
 'phiij',
 'radiusSquare',
 'spins',
 'threeBodyPotential',
 'threeBodyPotentialSpin',
 'twoBodyPotential',
 'u']

In [22]:
kin = np.array([[ 4.1869e-05 ,  6.2023e-05], [ 4.1869e-05  , 6.2023e-05]])
pot = np.array([[ -6.6094e-07 , -1.2543e-06], [-1.2543e-06 , -2.6992e-06]])
ham = kin + pot
gij = np.array([[4.4279e-08 ,  8.4113e-08], [8.4113e-08  , 1.8125e-07]])
cij = np.array([[3.8589e+03  , 1.3259e+04],[ -4.0461e+03 , -5.4966e+03]])
ham

array([[4.120806e-05, 6.076870e-05],
       [4.061470e-05, 5.932380e-05]])

In [27]:
ham1 = np.array([[930.66, 6.076870e-05],[4.061470e-05, 5.932380e-05]])
e,w = sp.linalg.eig(ham1)
gij**(1/2)

array([[0.00021043, 0.00029002],
       [0.00029002, 0.00042573]])

In [89]:
gij = np.array([[3.25767e-08 , 6.33712e-08],[6.33712e-08 , 1.48539e-07]])
cij = np.array([[4280.54 , 12734.1] , [-4285.62 , -4605.98]])
phij = np.array([[-0.000132138, -0.000365321],[0.000122948 , 0.000122802]])
print('gij: \n', gij,'\n','cij: \n',cij,'\n','phij: \n',phij)

gij: 
 [[3.25767e-08 6.33712e-08]
 [6.33712e-08 1.48539e-07]] 
 cij: 
 [[ 4280.54 12734.1 ]
 [-4285.62 -4605.98]] 
 phij: 
 [[-0.00013214 -0.00036532]
 [ 0.00012295  0.0001228 ]]


In [94]:
e,w = sp.linalg.eig(ham,gij)
print(np.sort(e),'\n','eigvec : \n',w)

[ 523.39756524+0.j 1716.10708365+0.j] 
 eigvec : 
 [[-0.94037355 -0.70668046]
 [ 0.34014347  0.70753285]]


In [98]:
np.linalg.inv(gij)@w.transpose()

array([[-1.15308373e+08,  6.91051701e+06],
       [ 4.44364747e+07,  1.81504581e+06]])

## The hamiltonian

In [13]:
gij = f['overlaps'][:]
gijT = np.transpose(gij)
e,w = np.linalg.eig(gij)
e = np.sort(e)
print('Overlaps inv: \n', np.linalg.inv(gij))
e,w = np.linalg.eig(np.linalg.inv(gij))

print(e)
# gijD = np.delete(gij,(29,28,27,26),0)
# gijD = np.delete(gijD,(29,28,27,26),1)
# e,w = np.linalg.eig(gijD)
# e = np.sort(e)
# print(e)
# giju, gijsv, gijv = np.linalg.svd(gij)
# print(gijsv)
# giju.resize(120,100)
# gijv.resize(100,120)
# #gijsv.resize(14,14)
# gijR = gijv@gij@giju
# print('orig overlaps:\n',gij)
# print('Resized overlaps:\n',gijR)
# gijR.shape

Overlaps inv: 
 [[ 3.20827480e+18  2.56305171e+16 -2.62107309e+16  7.87553674e+17
  -1.02117411e+18  4.38397426e+16 -3.49185468e+16  3.79691188e+16
  -1.80061305e+15 -4.63102244e+18 -2.24996753e+17 -5.51945762e+16
  -1.00365595e+17 -5.94242085e+15  2.02751630e+18  7.29868303e+16
   5.49452260e+16 -1.54808956e+15 -4.36191855e+16  5.08210874e+15
  -1.04172501e+17 -1.68316081e+16  1.96038297e+16 -1.44504945e+16
   7.44620434e+14 -2.08720713e+15 -2.50664692e+13  3.55568661e+13
   1.42002280e+14]
 [ 2.56307142e+16  6.80690113e+14 -5.21597337e+14  8.60614685e+15
  -6.59741394e+15  1.01375118e+15 -1.71672591e+15  3.02564309e+14
  -5.86258347e+13 -4.53199312e+16 -3.55647876e+14  5.58725920e+14
  -3.13670935e+15 -1.07960408e+14  1.89280000e+16  9.36966504e+14
   1.67072263e+15 -3.28117055e+13  1.21893209e+15  6.69420200e+14
  -2.31113061e+15 -1.88413008e+14  4.15451621e+14 -2.83367525e+14
   3.12776391e+13 -3.37996741e+13 -7.85765080e+11  1.39220373e+12
  -3.50655500e+11]
 [-2.62184084e+16 -5.2

In [17]:
kij = f['kinetic'][:]
kijD = np.delete(kij,(29,28,27,26),0)
kijD = np.delete(kijD,(29,28,27,26),1)

In [18]:
potij = f['twoBodyPotential'][:]
pijD = np.delete(potij,(29,28,27,26),0)
pijD = np.delete(pijD,(29,28,27,26),1)

In [19]:
hij = kij + potij
hijD = pijD + kijD
#hijR = gijv@hij@giju
print('ham: \n', hij)

ham: 
 [[-7.04067396e+00 -2.08579629e+01 -5.86571916e-01 ... -2.85192403e+00
  -4.73530329e+00 -8.56376299e+00]
 [-2.08579629e+01 -5.84935896e+01 -1.20336812e+00 ... -7.75710796e+00
  -1.46004882e+01 -3.35063379e+01]
 [-5.86571916e-01 -1.20336812e+00  2.31236075e-02 ... -1.95287562e-01
  -3.52573237e-01 -5.62298143e-01]
 ...
 [-2.85192403e+00 -7.75710796e+00 -1.95287562e-01 ... -1.02107120e+00
  -1.71536211e+00 -2.94108770e+00]
 [-4.73530329e+00 -1.46004882e+01 -3.52573237e-01 ... -1.71536211e+00
  -2.77701335e+00 -4.77495930e+00]
 [-8.56376299e+00 -3.35063379e+01 -5.62298143e-01 ... -2.94108770e+00
  -4.77495930e+00 -7.41528770e+00]]


### Eigenvalues finding in a std way

In [30]:
#print(np.linalg.inv(gij)@hij)
np.savetxt('diag.out',np.linalg.inv(gij)@hij, delimiter='  ')
e, w = sp.linalg.eig(hij,gij)
print(hij@gij - gij@hij)
#print("w shape: ", w.shape, " and w: \n", w)
e = np.sort(e)
print("Eigenvalues Ham: \n", e, e.shape)
# e, w = np.linalg.eig(np.linalg.inv(gijD)@hijD)
# #print("w shape: ", w.shape, " and w: \n", w)
# e = np.sort(e)
print("Eigenvalues Ham until nan: \n", e)
# H = w@np.diagflat(e)@w.transpose()
# H
# eN, wN = np.linalg.eig(np.linalg.inv(gijR)@hijR)
# eN = np.sort(eN)
# print("Eigenvalues New: \n", eN)

[[ 0.00000000e+00 -9.76193849e+04  3.44618382e+02 ...  1.71905523e+03
   2.01041591e+03 -3.36651132e+03]
 [ 9.76193849e+04  0.00000000e+00  4.98121652e+03 ...  3.58412991e+04
   7.37061565e+04  2.34740734e+05]
 [-3.44618382e+02 -4.98121652e+03  0.00000000e+00 ... -3.80761024e+01
  -1.52639783e+02 -9.19498948e+02]
 ...
 [-1.71905523e+03 -3.58412991e+04  3.80761024e+01 ...  0.00000000e+00
  -5.44272417e+02 -5.07007381e+03]
 [-2.01041591e+03 -7.37061565e+04  1.52639783e+02 ...  5.44272417e+02
   0.00000000e+00 -7.10237968e+03]
 [ 3.36651132e+03 -2.34740734e+05  9.19498948e+02 ...  5.07007381e+03
   7.10237968e+03  0.00000000e+00]]
Eigenvalues Ham: 
 [-2.62464843+0.j -0.42625834+0.j -0.28787843+0.j -0.09823773+0.j
  0.12792546+0.j  0.21203935+0.j  0.3483461 +0.j  0.40534507+0.j
  0.52211747+0.j  0.77957505+0.j  0.91017097+0.j  1.08115284+0.j
  1.15861995+0.j  1.49674699+0.j  1.65253932+0.j  1.83497561+0.j
  2.23400302+0.j  2.57859133+0.j  3.11755919+0.j  3.29573933+0.j
  3.44235265+0.j  4.

### Eigenvalues finding by svd

In [21]:
u,s,v = np.linalg.svd(hij)
print("u shape: ", u.shape, " and u: \n", u)
print("v shape: ", v.shape, " and v: \n", v)
print("Singular values: \n", s)
Hsv = u@np.diagflat(s)@v
Hsv

u shape:  (35, 35)  and u: 
 [[-3.74826204e-02  1.51893361e-02  5.66852105e-02 ... -7.77867254e-02
  -1.04955916e-01 -4.38189811e-02]
 [-1.35788578e-01  1.15834173e-01  5.61864182e-02 ...  7.27972859e-04
  -5.51818432e-01  2.61121454e-01]
 [-1.59882259e-03 -8.15993536e-04  4.57938823e-04 ...  1.91249543e-02
  -5.08848318e-03  5.21958725e-03]
 ...
 [-1.18391449e-02  2.72528223e-04  1.54040989e-02 ... -1.16210549e-01
  -8.76615151e-02 -1.13447058e-01]
 [-2.54238804e-02  1.07350533e-02  4.45323375e-02 ... -1.80710475e-01
  -1.65947966e-02 -6.28278619e-02]
 [-8.70879996e-02  1.20786686e-01  1.58523709e-01 ... -2.73542124e-02
   1.04711630e-02  6.48372825e-02]]
v shape:  (35, 35)  and v: 
 [[ 3.74826204e-02  1.35788578e-01  1.59882259e-03 ...  1.18391449e-02
   2.54238804e-02  8.70879996e-02]
 [ 1.51893361e-02  1.15834173e-01 -8.15993536e-04 ...  2.72528223e-04
   1.07350533e-02  1.20786686e-01]
 [ 5.66852105e-02  5.61864182e-02  4.57938823e-04 ...  1.54040989e-02
   4.45323375e-02  1.58523

array([[-7.04067396e+00, -2.08579629e+01, -5.86571916e-01, ...,
        -2.85192403e+00, -4.73530329e+00, -8.56376299e+00],
       [-2.08579629e+01, -5.84935896e+01, -1.20336812e+00, ...,
        -7.75710796e+00, -1.46004882e+01, -3.35063379e+01],
       [-5.86571916e-01, -1.20336812e+00,  2.31236075e-02, ...,
        -1.95287562e-01, -3.52573237e-01, -5.62298143e-01],
       ...,
       [-2.85192403e+00, -7.75710796e+00, -1.95287562e-01, ...,
        -1.02107120e+00, -1.71536211e+00, -2.94108770e+00],
       [-4.73530329e+00, -1.46004882e+01, -3.52573237e-01, ...,
        -1.71536211e+00, -2.77701335e+00, -4.77495930e+00],
       [-8.56376299e+00, -3.35063379e+01, -5.62298143e-01, ...,
        -2.94108770e+00, -4.77495930e+00, -7.41528770e+00]])

<h3> U matrix to rotate to cartesian coordinate <b> r </b> to jacobi ones <b> x </b> </h3>

In [22]:
U = np.array([[1,-1,0],[1/2,1/2,-1],[1/3,1/3,1/3]])
U_1 = np.linalg.inv(U)
print('U: \n',U)
print('U-1: \n',U_1)

U: 
 [[ 1.         -1.          0.        ]
 [ 0.5         0.5        -1.        ]
 [ 0.33333333  0.33333333  0.33333333]]
U-1: 
 [[ 0.5         0.33333333  1.        ]
 [-0.5         0.33333333  1.        ]
 [ 0.         -0.66666667  1.        ]]


<h3> W matrix to pass from the relative cartesian coordinate <b> r<sub>i</sub> - r<sub>j</sub> </b> to jacobi ones <b> x </b> </h3>

In [23]:
pairs = np.array([[0,1],[0,2],[1,2]])
W = np.zeros((3,3))
for i in range(3):
    W[i] = U_1[pairs[i,0],:]-U_1[pairs[i,1],:]
W = W[:,0:2]
print('W:',W)

W: [[ 1.   0. ]
 [ 0.5  1. ]
 [-0.5  1. ]]


<h3> Passing from &alpha;s to A matrix </h3>

In [24]:
alphas = np.diagflat([[0.24529942, 0.00132671, 0.00272581]])
A = W.transpose()@alphas@W
B = A + A
print('alphas: \n',alphas)
print('A: \n',A)
print('B: \n',B)

alphas: 
 [[0.24529942 0.         0.        ]
 [0.         0.00132671 0.        ]
 [0.         0.         0.00272581]]
A: 
 [[ 0.24631255 -0.00069955]
 [-0.00069955  0.00405252]]
B: 
 [[ 0.4926251  -0.0013991 ]
 [-0.0013991   0.00810504]]


<h3> &Lambda; for kinetic energy </h3>

In [25]:
Lambda = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        tmpMat = U[i,:]*U[j,:]
        Lambda[i,j] = tmpMat.sum()
print('Lambda : \n', Lambda)

Lambda : 
 [[2.  0. ]
 [0.  1.5]]


In [26]:
R = 3.*np.trace(A@np.linalg.inv(B)@A@Lambda)
R

0.74805582

<h3> Kinetic Energy </h3>

In [27]:
K = R/48./math.pi*(4.*math.pi**2/np.linalg.det(B))**1.5
K

4880.838154930869

### Overlaps

In [28]:
overlaps = 1/24./math.pi*((2*math.pi)**2/np.linalg.det(B))**1.5
overlaps

13049.395578342985